//
//  StatusMessageModels.swift
//  Back2Back
//
//  Created on 2025-10-05.
//  Models for dynamic status messages using Foundation Models framework
//

import Foundation
import FoundationModels

/// Three persona-specific status messages generated by Foundation Models
/// Uses @Generable macro for structured output from SystemLanguageModel
@Generable
struct StatusMessages: Codable, Equatable, Sendable {
    let message1: String
    let message2: String
    let message3: String
}

/// Cached status messages with usage tracking for regeneration
struct CachedStatusMessages: Codable, Sendable {
    let messages: StatusMessages
    let personaId: UUID
    let generatedAt: Date
    var usageCount: Int

    /// Determines if messages should be regenerated
    /// Regenerates after 10 uses to keep content fresh
    var shouldRegenerate: Bool {
        usageCount >= 10
    }
}
